app:
  port: 8080
database:
  type: sqlite # Replace with postgres
  sqlite_path: sqlite_short_urls.db 
  postgres_host: 127.0.0.1
  postgrest_port: 5432
  postgres_user: user
  postgres_password: password
  postgres_db_name: db
worker:
  identifier: A